application: nus-cca-finder
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

# favicon
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# self-defined css
- url: /stylesheets
  static_dir: stylesheets

# images
- url: /images
  static_dir: images

# self-defined scripts-js
- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: front.app

# Handler for login and redirection
- url: /_ah/login_required
  script: login.app

# pages require login: general pages
- url: /(index|profile|editprofile|search|display|img)
  script: general.app
  login: required

# pages require admin: edit/add cca
- url: /CCA/(edit|add)
  script: cca.app
  login: required

- url: /interst
  script: cca.app
  login: required

# pages does not require login
- url: /CCA/(view|comment)
  script: cca.app

- url: /view/(guide|all-halls|hall|all-categories|category|search)
  script: view.app

# pages not found
- url: /.*
  script: not-found.app

libraries:
- name: jinja2
  version: latest